---
- hosts: staging
  become: true
  gather_facts: false
  tasks:
    - name: update apt cache
      apt: update_cache=yes cache_valid_time=86400
      tags: [ 'packages'] 
- import_playbook: playbooks/example-production.yml
